apiVersion: v1
baseDomain: tale.net
metadata:
  name: ocp4
networking:
  networkType: OVNKubernetes
  machineCIDR: 192.168.30.0/24
compute:
- name: worker
  replicas: 2
controlPlane:
  name: master
  replicas: 3
  platform:
        baremetal: {}
platform:
  baremetal:
    apiVIP: 192.168.30.100
    ingressVIP: 192.168.30.110
    provisioningNetwork: "Disabled"
    externalBridge: baremetal
    hosts:
      - name: bmipi-master0
        role: master
        bmc:
          address: redfish-virtualmedia://172.31.75.189:8080/redfish/v1/Systems/2451...4bc82
          disableCertificateVerification: True
          username: admin
          password: password
        bootMACAddress: 52:54:00:74:dc:a0
        bootMode: legacy
        hardwareProfile: libvirt
        rootDeviceHints:
            deviceName: /dev/vda
      - name: bmipi-master1
        role: master
        bmc:
          address: redfish-virtualmedia://172.31.75.189:8080/redfish/v1/Systems/a95336...6ec
          disableCertificateVerification: True
          username: admin
          password: password
        bootMACAddress: 52:54:00:74:dc:a1
        bootMode: legacy
        hardwareProfile: libvirt
        rootDeviceHints:
            deviceName: /dev/vda
      - name: bmipi-master2
        role: master
        bmc:
          address: redfish-virtualmedia://172.31.75.189:8080/redfish/v1/Systems/36a1...7cb8e
          disableCertificateVerification: True
          username: admin
          password: password
        bootMACAddress: 52:54:00:74:dc:a2
        bootMode: legacy
        hardwareProfile: libvirt
        rootDeviceHints:
            deviceName: /dev/vda
      - name: bmipi-worker0
        role: worker
        bmc:
          address: redfish-virtualmedia://172.31.75.189:8080/redfish/v1/Systems/11ad...4a489
          disableCertificateVerification: True
          username: admin
          password: password
        bootMACAddress: 52:54:00:74:dc:d0
        bootMode: legacy
        hardwareProfile: libvirt
        rootDeviceHints:
            deviceName: /dev/vda
      - name: bmipi-worker1
        role: worker
        bmc:
          address: redfish-virtualmedia://172.31.75.189:8080/redfish/v1/Systems/639...5a7a4e
          disableCertificateVerification: True
          username: admin
          password: password
        bootMACAddress: 52:54:00:74:dc:d1
        bootMode: legacy
        hardwareProfile: libvirt
        rootDeviceHints:
            deviceName: /dev/vda
pullSecret: ‘’
sshKey: |
