apiVersion: local.storage.openshift.io/v1
kind: LocalVolume
metadata:
  name: vol2
  namespace: openshift-local-storage
spec:
  nodeSelector: 
    nodeSelectorTerms:
    - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - worker1.ocp4.tale.net
          - worker2.ocp4.tale.net
  storageClassDevices:
    - devicePaths:
        - /dev/vdb
      fsType: ext4
      storageClassName: registorage
      volumeMode: Filesystem
