apiVersion: v1
basedomain: tale.net
metadata:
  name: ocp4
networking:
  machineNetwork:
  - cidr: 192.168.30.0/24
  networkType: OVNKubernetes
compute:
- name: worker
  replicas: 2
controlPlane:
  name: master
  replicas: 3
  platform:
        baremetal: {}
platform:
  baremetal:
    apiVIP: 192.168.30.100
    ingressVIP: 192.168.30.110
    provisioningDHCPRange: 192.168.14.20,192.168.14.100
    provisioningBridge: provision
    externalBridge: chucky
    provisioningNetworkCIDR: 192.168.14.0/24
    hosts:
      - name: bmipi-master1
        role: master
        bmc:
          address: ipmi://192.168.30.1:7001
          disableCertificateVerification: true
          username: admin
          password: secreto
        bootMACAddress: 52:54:00:74:dc:a1
        hardwareProfile: libvirt
      - name: bmipi-master2
        role: master
        bmc:
          address: ipmi://192.168.30.1:7002
          disableCertificateVerification: true
          username: admin
          password: secreto
        bootMACAddress: 52:54:00:74:dc:a2
        hardwareProfile: libvirt
      - name: bmipi-master3
        role: master
        bmc:
          address: ipmi://192.168.30.1:7003
          disableCertificateVerification: true
          username: admin
          password: secreto
        bootMACAddress: 52:54:00:74:dc:a3
        hardwareProfile: libvirt
      - name: bmipi-worker1
        role: worker
        bmc:
          address: ipmi://192.168.30.1:7011
          disableCertificateVerification: true
          username: admin
          password: secreto
        bootMACAddress: 52:54:00:74:dc:d1
        hardwareProfile: libvirt
      - name: bmipi-worker2
        role: worker
        bmc:
          address: ipmi://192.168.30.1:7012
          disableCertificateVerification: true
          username: admin
          password: secreto
        bootMACAddress: 52:54:00:74:dc:d2
        hardwareProfile: libvirt
pullSecret: '...'
sshKey: |
